// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallCreator(arg1:string,arg2:string,arg3:string):Promise<number>;

export function SelectOriginalPE():Promise<string>;

export function SetSavePath():Promise<string>;
