// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallCreator(arg1, arg2, arg3) {
  return window['go']['main']['App']['CallCreator'](arg1, arg2, arg3);
}

export function SelectOriginalPE() {
  return window['go']['main']['App']['SelectOriginalPE']();
}

export function SetSavePath() {
  return window['go']['main']['App']['SetSavePath']();
}
